# Generated by Django 5.2.3 on 2025-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_for_rent', models.BooleanField(default=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
